# Site settings
description: Blog sobre programación y noticias de software libre, lenguajes c++, java, python, android, bases de datos, sql y pl/sql
# baseurl:
url: https://elbauldelprogramador.com
locale: es_ES
title: El Baúl del programador

# User settings
username: Alejandro Alcalde
user_description: Estudiante de Grado en Ingeniería Informática en la ETSIIT, Granada. Especialidad, Inteligencia Artificial.
user_title: Alejandro Alcalde
email: contacto@elbauldelprogramador.com
twitter_username: elbaulp
github_username:  algui91
gplus_username:  ElBauldelProgramador
disqus_username: bashyc

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
gems:
  - jekyll-sitemap

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Categorías
    url: /categorias
  - title: Tags
    url: /tags
  - title: Cursos
    url: /cursos/
  - title: Manuales
    url: /manuales-gratuitos/
  - title: Security Now!
    url: /security-now/
  - title: Apoyanos
    url: /apoyanos/
  - title: Contacto
    url: /contacto


# Site owner
owner:
  name: Alejandro Alcalde
  avatar: alejandro.jpg
  bio: "Estudiante de Grado en Ingeniería Informática en la ETSIIT, Granada. Especialidad, Inteligencia Artificial."
  email: contacto@elbauldelprogramador.com
  disqus-shortname: bashyc
  twitter: elbaulp
  facebook: elbauldelprogramador
  google:
    plus: elbauldelprogramador
    analytics: UA-19017085-2
    verify: FBg0GK1_H_PyCw6AD2iaBOclPbEC3LOV8hHXje5276w
    ad-client: ca-pub-9043332344373532
    # ad-slot: 9782918042
    # ad-slot2: 2727042844
    ad-slot3: 2633319248
  bsa: false
  amazon:
    id: elbaudelpro-21
  bing-verify:
  github: algui91
  stackoverflow: 1612432/algui91
  stackcareers: algui91
  linkedin: algui91

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
