# Site settings
description: A blog about lorem ipsum dolor sit amet
baseurl: https://elbauldelprogramador.com "" # the subpath of your site, e.g. /blog
url: https://elbauldelprogramador.com

# User settings
username: Lorem Ipsum
user_description: Anon Developer at Lorem Ipsum Dolor
user_title: Anon Developer
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: https://elbauldelprogramador.com /
  - title: Series
    url: https://elbauldelprogramador.com /series
  - title: Tags
    url: https://elbauldelprogramador.com /tags
  - title: About Me
    url: https://elbauldelprogramador.com /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
